apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpserver
  namespace: istio-system
spec:
  dnsNames:
  - httpserver.01.com
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-prod
  secretName: httpserver
  usages:
    - digital signature
    - key encipherment