apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
# 类属性键；每一个键都映射到一个简单的值
  player_initial_lives: "3"
  loglevel: debug
volumes:
- name: config
  configMap:
    name: game-demo
env:
- name:  PLAYER_INITIAL_LIVES
  valueFrom:
    configMapKeyRef:
      name: game-demo
      key: player_initial_lives